name: Update GitHub Streak Stats

on:
  schedule:
    - cron: "0 3 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  streak:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub streak stats
        uses: zients/github-readme-streak-stats@v2
        with:
          options: user=dileepvgowda18&theme=dark&hide_border=false&disable_animations=true
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit updated streak
        run: |
          git add profile/streak.svg

          if git diff --cached --quiet -- profile/streak.svg; then
            echo "No streak changes."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git commit -m "Update GitHub streak stats"
          git push
